server:
  port: 8083

spring:
  application:    name: labmanage-server
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/labmanage?allowPublicKeyRetrieval=true & useSSL=false
    username: labmanage
    password: lab
    type: com.zaxxer.hikari.HikariDataSource
  rabbitmq:    host: localhost
    port: 5672
    username: guest
    password: guest
    
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#    interceptions: com.ncepu.feilong505.OASystem.Common.BaseMapperInterceptor
#  config-location: classpath*:mybatis-config.xml
  type-aliases-package: com.ncepu.feilong505.LabManage.pojo
  mapperLocations: classpath*:com/ncepu/feilong505/LabManage/mapper/xml/*.xml
#  type-aliases-package: com/ncepu/feilong505/OASystem/Model
logging:
  level:
    root: info
    



  
  
 
  
    